language: java

jdk:
  - openjdk8
  - openjdk11

addons:
  apt:
    packages:
      - openjfx
#      - oracle-java8-installer
#      - oracle-java9-installer

dist: trusty
sudo: false

notifications:
  email:
    recipients:
      - dev@speedment.com
    on_success: never  # default: change
    on_failure: always # default: always

